version: '3.7'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django-backend
    command: gunicorn image_loader.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/image/backend/static
      - media_volume:/home/image/backend/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/image/backend/static
      - media_volume:/home/image/backend/media
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.database

volumes:
  postgres_data:
  static_volume:
  media_volume: