# Generated by Django 3.2.3 on 2021-05-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0003_auto_20210517_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplan_plan', to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userplan_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
