# Generated by Django 3.2.3 on 2021-05-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210517_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
